package Principal;

import Clases.Conexion;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 *
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        //jPanel1 = new Imagen("C:\\Users\\Reymundo Tenorio\\Documents\\NetBeansProjects\\Indira\\src\\Principal\\Ejercito.jpg");
        jPanel1 = new Imagen("Banco.jpg");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu5.setText("Banco");

        jMenuItem1.setText("Ver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Agregar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Sucursal");

        jMenuItem21.setText("Ver");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem21);

        jMenuItem22.setText("Agregar");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem22);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vigilante");

        jMenuItem25.setText("Ver");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem25);

        jMenuItem26.setText("Agregar");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem26);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cuartel");

        jMenuItem29.setText("Ver");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem29);

        jMenuItem30.setText("Agregar");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem30);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Cuerpo");

        jMenuItem33.setText("Ver");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem33);

        jMenuItem34.setText("Agregar");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem34);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Reportes");

        jMenuItem23.setText("Banco");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem23);

        jMenuItem24.setText("Sucursal");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem24);

        jMenuItem27.setText("Compañia");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem27);

        jMenuItem28.setText("Cuerpo");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem28);

        jMenuItem31.setText("Cuartel");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem31);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
Agregar_Banco AS = new Agregar_Banco();
AS.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
Agregar_Sucursal AG = new Agregar_Sucursal();
AG.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
Agregar_Vigilante AC = new Agregar_Vigilante();
AC.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
Agregar_Cuartel AC = new Agregar_Cuartel();
AC.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
Agregar_Cuerpo AC = new Agregar_Cuerpo();
AC.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
Ver_Banco VS = new Ver_Banco();
VS.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
Ver_Sucursal VS = new Ver_Sucursal();
VS.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
Ver_Cuartel VC = new Ver_Cuartel();
VC.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
Ver_Cuerpo VC = new Ver_Cuerpo();
VC.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
Ver_Vigilante VC = new Ver_Vigilante();
VC.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed

        JasperReport Reporte = null;
           /*  CUANDO SE CREA EL REPORTE EN LA RAIZ DEL PROYECTO SOLO
            SE MANDA EL NOMBRE DEL REPORTE, EN CASO CONTRARIO SE MANDA LA
            URL ABSOLUTA (DIRECCION COMPLETA)*/
        
        String Nombre = "Banco.jasper";
        
        File F = new File("");
        String Ruta = F.getAbsolutePath();
        
        
        Ruta = Ruta.concat("\\src\\Reporte\\").concat(Nombre);
       
             try{
               
                     Reporte = (JasperReport) JRLoader.loadObject(Ruta);
            
             JasperPrint RP;
       
            RP = JasperFillManager.fillReport(Reporte, null, Conexion.con);
            
       
             
             JasperViewer Vista  = new JasperViewer(RP, false);
             Vista.setTitle("Bancos");
             Vista.setVisible(true);
        
 }  catch(JRException ex){
             JOptionPane.showMessageDialog(null, "Error Con Reporte");
             }

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
    JasperReport Reporte = null;
           /*  CUANDO SE CREA EL REPORTE EN LA RAIZ DEL PROYECTO SOLO
            SE MANDA EL NOMBRE DEL REPORTE, EN CASO CONTRARIO SE MANDA LA
            URL ABSOLUTA (DIRECCION COMPLETA)*/
        
        String Nombre = "Sucursal.jasper";
        
        File F = new File("");
        String Ruta = F.getAbsolutePath();
        
        
        Ruta = Ruta.concat("\\src\\Reporte\\").concat(Nombre);

       
             try{
               
                     Reporte = (JasperReport) JRLoader.loadObject(Ruta);
            
             JasperPrint RP;
       
            RP = JasperFillManager.fillReport(Reporte, null, Conexion.con);
            
       
             
             JasperViewer Vista  = new JasperViewer(RP, false);
             Vista.setTitle("Sucursal");
             Vista.setVisible(true);
        
 }  catch(JRException ex){
             JOptionPane.showMessageDialog(null, "Error Con Reporte");
             }

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
  JasperReport Reporte = null;
           /*  CUANDO SE CREA EL REPORTE EN LA RAIZ DEL PROYECTO SOLO
            SE MANDA EL NOMBRE DEL REPORTE, EN CASO CONTRARIO SE MANDA LA
            URL ABSOLUTA (DIRECCION COMPLETA)*/
             try{
               
                     Reporte = (JasperReport) JRLoader.loadObject("C:\\Users\\Reymundo Tenorio\\Documents\\NetBeansProjects"
                             + "\\Indira\\src\\Principal\\Compania.jasper");
            
             JasperPrint RP;
       
            RP = JasperFillManager.fillReport(Reporte, null, Conexion.con);
            
       
             
             JasperViewer Vista  = new JasperViewer(RP, false);
             Vista.setTitle("Compañia");
             Vista.setVisible(true);
        
 }  catch(JRException ex){
             JOptionPane.showMessageDialog(null, "Error Con Reporte");
             }
      
        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
  JasperReport Reporte = null;
           /*  CUANDO SE CREA EL REPORTE EN LA RAIZ DEL PROYECTO SOLO
            SE MANDA EL NOMBRE DEL REPORTE, EN CASO CONTRARIO SE MANDA LA
            URL ABSOLUTA (DIRECCION COMPLETA)*/
             try{
               
                     Reporte = (JasperReport) JRLoader.loadObject("C:\\Users\\Reymundo Tenorio\\Documents\\NetBeansProjects"
                             + "\\Indira\\src\\Principal\\Cuerpo.jasper");
            
             JasperPrint RP;
       
            RP = JasperFillManager.fillReport(Reporte, null, Conexion.con);
            
       
             
             JasperViewer Vista  = new JasperViewer(RP, false);
             Vista.setTitle("Cuerpo");
             Vista.setVisible(true);
        
 }  catch(JRException ex){
             JOptionPane.showMessageDialog(null, "Error Con Reporte");
             }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
  JasperReport Reporte = null;
           /*  CUANDO SE CREA EL REPORTE EN LA RAIZ DEL PROYECTO SOLO
            SE MANDA EL NOMBRE DEL REPORTE, EN CASO CONTRARIO SE MANDA LA
            URL ABSOLUTA (DIRECCION COMPLETA)*/
             try{
               
                     Reporte = (JasperReport) JRLoader.loadObject("C:\\Users\\Reymundo Tenorio\\Documents\\NetBeansProjects"
                             + "\\Indira\\src\\Principal\\Cuartel.jasper");
            
             JasperPrint RP;
       
            RP = JasperFillManager.fillReport(Reporte, null, Conexion.con);
            
       
             
             JasperViewer Vista  = new JasperViewer(RP, false);
             Vista.setTitle("Cuartel");
             Vista.setVisible(true);
        
 }  catch(JRException ex){
             JOptionPane.showMessageDialog(null, "Error Con Reporte");
             }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
