go
use Seguridad_Bancaria
/*Insertar Vigilante usando procedimientos almacenados*/
go
NVIGILANTE 'Anger','Mike','Duran','Gibson','601-270192-0001T', 'M',22
go
NVIGILANTE	'Alvin', 'Antonio','Araica','Perez','401-020792-0000O','M',21
go
NVIGILANTE  'DANIEL', 'Francisco','ACEVEDO', 'JHONG','201-010192-0001F','M',22
go
NVIGILANTE 'MIGUEL', 'VICENTE','AGURTO', 'RONDOY','001-020585-0010S','M',29 
go
NVIGILANTE 'CHRISTIAN', 'NELSON','ALCALÁ', 'NEGRÓN','401-270170-0090L','M',44 
go
NVIGILANTE 'RAUL' ,'EDUARDO','ALMORA', 'HERNANDEZ','261-311265-0024F','M',49 
go
NVIGILANTE  'JORGE', 'ANTONIO', 'VELAZCO', 'VERA','001-140793-0014Q','M',21 
go
NVIGILANTE 'VICTOR','MANUEL','ALVA', 'CAMPOS','202-140273-0001S','M',41
go
NVIGILANTE 'FRANCISCO','JAVIER','AREVALO', 'LOPEZ','401-140380-0045M','M',34 
go
NVIGILANTE 'ROSARIO','MARGARITA','ARIAS', 'HERNANDEZ','201-080484-0024A','F',30
go
NVIGILANTE 'EFRAÍN', 'JOSE','ARROYO', 'RAMÍREZ','401-100890-0046W','M',24 
go
NVIGILANTE 'MARCO', 'TULIO','ALOCEN', 'BARRERA','201-150979-0047L','M',35 
/*
go
NVIGILANTE 
BAIOCCHI URETA, CESAR
go
NVIGILANTE 
BAYLÓN ROJAS, ISELA FLOR
go
NVIGILANTE 
BEDOYA CASTILLO, LEONCIA
go
NVIGILANTE 
BEDREGAL CANALES, LUZ MARINA
go
NVIGILANTE 
BEJAR TORRES, RAMIRO ALBERTO
go
NVIGILANTE 
BENAVIDES ESPEJO, JAVIER
go
NVIGILANTE 
BOZA SOLIS, NELSON
go
NVIGILANTE 
CALLE BETANCOURT, CIELITO MERCEDES
go
NVIGILANTE 
CARAZA VILLEGAS, ISABEL FLORISA
go
NVIGILANTE 
CARRERA ABANTO, GIZELLA
go
NVIGILANTE 
CARRILLO SEGURA, ESTALINS
go
NVIGILANTE 
CARRIÓN NEIRA, JORGE AUGUSTO
go
NVIGILANTE 
CASAPIA VALDIVIA, GUILLERMO 
go
NVIGILANTE 
CHANCOS MENDOZA, ZARITA
go
NVIGILANTE 
CHIRINOS LACOTERA, CARLOS
go
NVIGILANTE 
CORES MORENO, DORIS
go
NVIGILANTE 
CORTEZ LOZANO, MARIBEL CORINA
go
NVIGILANTE 
CRISPIN QUISPE, ANGEL
go
NVIGILANTE 
DE LOAYZA CONTERNO, ANTONIO 
go
NVIGILANTE 
DIAZ SALINAS, ANA MARIA
go
NVIGILANTE 
DUEÑAS ARISTISABAL, ANTONIO
go
NVIGILANTE  
ESPINOZA ARANA, YULIANA
go
NVIGILANTE 
FERNANDEZ GUZMAN, CARLOS ENRIQUE
go
NVIGILANTE 
FERNANDEZ MATTA, ESTHER AURORA
go
NVIGILANTE 
FERRO SALAS, OLGA
go
NVIGILANTE 
FLORES ROMERO, EDWIN
go
NVIGILANTE 
GAMARRA ASTETE, ROBERTO
go
NVIGILANTE 
GAMIO LOZANO, GLORIA
go
NVIGILANTE 
GARCÍA PERALTA, MIRIAM
go
NVIGILANTE 
GONZALES DEL VALLE MAGUIÑO, ARTURO
go
NVIGILANTE 
GONZALES HUILCA, MARLENE VICTORIA
go
NVIGILANTE 
GONZALES MEDINA, ELSA PATRICIA
go
NVIGILANTE 
GUTIERREZ VELEZ, JAVIER
go
NVIGILANTE 
GUZMAN CHINAG, ELENA ROSAVELT
go
NVIGILANTE 
GUZMAN QUISPE, CLARA
go
NVIGILANTE 
HERRERA CARBAJAL, MILAGROS SUSAN
go
NVIGILANTE  
HORRUITINER MARTINEZ, GUILLERMO
go
NVIGILANTE 
HUAMANI FLORES, LOURDES
go
NVIGILANTE 
HUAPAYA RAYGADA, LUIS ARMANDO
go
NVIGILANTE 
HUARCAYA QUISPE, MARCOS
go
NVIGILANTE 
HUAYTAN SAUÑE, WALTER DAVID
go
NVIGILANTE 
LA ROSA FABIAN, ELBA MERCEDES 
go
NVIGILANTE 
LANDA GINOCCHIO, PEDRO GUILLERMO
go
NVIGILANTE 
LLAJA TAFUR, ROBERTO JULIAN
go
NVIGILANTE 
LLENPEN NUÑEZ, ORFELINA
go
NVIGILANTE 
LUJAN VENEGAS, HECTOR
go
NVIGILANTE 
MAGUIÑA SAN YEN MAN, GISSELA
go
NVIGILANTE 
MALDONADO QUISPE, COSME ADOLFO
go
NVIGILANTE 
MALDONADO TINCO, SANDRA MONICA
go
NVIGILANTE 
MALLQUI CELESTINO, JENNY MARIA
go
NVIGILANTE 
MAMANI UCHASARA, SANTIAGO
go
NVIGILANTE 
MARAVI NAVARRO, MAGDA JANETH
go
NVIGILANTE 
MARTINEZ MARQUEZ, MARTIN
go
NVIGILANTE 
MEDINA ZUTA, OSCAR ENRIQUE
go
NVIGILANTE 
MELGAREJO VIBES, CARLOS 
go
NVIGILANTE 
MIGUEL HOLGADO, ELIZABETH
go
NVIGILANTE 
MORI RAMIREZ, MANUEL ANTONIO
go
NVIGILANTE 
NUÑEZ HUAYANAY, CARLOS ALBERTO
go
NVIGILANTE 
ORE REYES, OLGA
go
NVIGILANTE 
ORRILLO ORTIZ, JOSUE
go
NVIGILANTE 
ORRILLO ORTIZ, JOSUÉ VICTOR
go
NVIGILANTE 
PARDAVE CAMACHO, CARMEN ROSA
go
NVIGILANTE 
PAREDES JARAMILLO, SANTIAGO VICTOR
go
NVIGILANTE 
PASTOR PORRAS, ARTURO
go
NVIGILANTE 
PINEDO NUÑEZ, ENRIQUE
go
NVIGILANTE 
PRADA VILCHEZ, SONIA
go
NVIGILANTE 
RIEGA CALLE, GERARDO DAVID
go
NVIGILANTE 
RIOS LIMA, FREDDY
go
NVIGILANTE 
RIOS LIMA, TERESA
go
NVIGILANTE 
RIQUELME MIRANDA, JUAN ELVIS
go
NVIGILANTE 
ROA YANAC, GEORGINA ESPERANZA
go
NVIGILANTE 
ROBLES VALVERDE, ROSA LILIANA
go
NVIGILANTE 
RODRIGUEZ FARIAS, ROSA JOSEFA
go
NVIGILANTE 
ROJAS VALDIVIA, MARIA DE FATIMA
go
NVIGILANTE 
ROMERO GOMEZ SANCHEZ, ROSA MARIA
go
NVIGILANTE 
ROSALES FLORES, CARINA MAGNOLIA
go
NVIGILANTE 
ROSAS BONIFAZ, CARLOS JOSE
go
NVIGILANTE 
RUIZ DE CASTILLA BRITTO, AIDA CRISTINA
go
NVIGILANTE 
SALCEDO DEL PINO, CELIN
go
NVIGILANTE 
SALINAS PUCCIO, VIOLETA MARILU
go
NVIGILANTE 
SANCHEZ ARONE, AUGUSTO
go
NVIGILANTE 
SANTA CRUZ BENSSA, PEDRO MANUEL
go
NVIGILANTE 
SOLANO VARGAS, ANGEL
go
NVIGILANTE 
TEJEDO LUNA, JOSE ALBERTO
go
NVIGILANTE 
TENORIO DAVILA, ANGEL 
go
NVIGILANTE 
TORRES GASPAR, MIGUEL ANGEL 
go
NVIGILANTE 
TRUJILLO PARODI, JACQUELIN
go
NVIGILANTE 
VEGA CARREAZO, RUTH NORICILA
go
NVIGILANTE 
VELASQUEZ RAMOS, GUILLERMO JONATHAN
go
NVIGILANTE 
VERA SILVA, ALEJANDRO
go
NVIGILANTE 
VILCA LUCERO, BLANCA KATTY
go
NVIGILANTE 
VILGOSO ALVARADO, ENRIQUE GODOFREDO
go
NVIGILANTE 
YAMAWAKI ONAGA, CECILIA
go
NVIGILANTE 
ZAMALLOA VEGA, MARIELA MILAGROS
go
NVIGILANTE 
ZAPATA CHANG, MONICA 
go
NVIGILANTE 
ZEGARRA SALCEDO, JUAN CARLOS
go
NVIGILANTE 
ZU FLORES, HILRICH MARIELA
go*/

/*Consultar Vigilante*/
go
select * from Vigilante